### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by merwy** [mtanda/grafana-heatmap-epoch-panel#4] opened 2016-05-30 10:07 UTC
Hi,

I'm using Grafana 3.0 with InfluxDB and can't make this heatmap working. No content is displayed. Is there any trick that needs to be done in the query to make it work?

**Comment by mtanda** [comment] 2016-05-31 15:45
Oops, I test it with latest Grafana, it doesn't work now.
I'll check the error and fix it.

**Comment by Pawcio4** [comment] 2016-06-01 07:00
Please do, we really would like to use heatmap functionality.

**Comment by mtanda** [comment] 2016-06-01 16:12
The problem might be caused by legend name handling.
If it doesn't contains symbol characters, it works.
I'll fix the issue in this week.

**Comment by mtanda** [comment] 2016-06-02 14:04
I fix the error (in my env).
Would you update the plugin and test it?

**Comment by merwy** [comment] 2016-06-02 14:32
Yes. Sure. Thanks!

**Comment by merwy** [comment] 2016-06-06 06:58
I still can't make it work. Whatever query I make, nothing is displayed on the panel. Can you share example of the correct query for influxdb to make it work.

**Comment by mtanda** [comment] 2016-06-07 04:00
Sorry for late reply.
Personally I don't use InfluxDB, I use Prometheus.
I install Grafana 3.0.4-1464167696 release version, and add panel, it works.

![heatmap](https://cloud.githubusercontent.com/assets/224552/15845598/7fb09b3e-2caf-11e6-9127-8e8efc8dc6fc.png)

Can you share screenshot, and if there are error dialog, please share error message.

**Comment by merwy** [comment] 2016-06-07 08:08
Let me explain my query. However I’m not sure if this is correct query for your heatmap.
I want to show a heatmap of average CPU load where dimensions are time and racks. Time dimension should be drawn on X-axis and different racks should be drawn on Y-axis. I’m not sure if I should use GROUP BY to define dimensions (axis) for the heatmap.
To achieve this, I have the following query in Grafana:

![1](https://cloud.githubusercontent.com/assets/19647399/15850310/9a1beef0-2c97-11e6-863e-8953327f440c.png)

Unfortunately, as a result of this, nothing is drawn on the panel.

![2](https://cloud.githubusercontent.com/assets/19647399/15850283/785b2376-2c97-11e6-8afc-7e3c5f06c41b.png)

Interesting is that after saving a dashboard, going to some other dashboard, and going back to dashboard with heatmap, the following error occurs on the panel: _t is undefined_

![3](https://cloud.githubusercontent.com/assets/19647399/15850256/536c2826-2c97-11e6-859c-62f02f0c5fa5.png)

**Comment by mtanda** [comment] 2016-06-07 08:33
I notice that the query editor has some bug, so the error is shown after dashboard save, might be caused by the bug.
And, I don't know well about InfluxDB query, is the query can draw on normal Graph panel?

**Comment by sikadiamond** [comment] 2016-07-08 08:38
I'm also strugeling to make it work, could you provide an example db & query for influxdb?

**Comment by mtanda** [comment] 2016-07-08 09:11
@sikadiamond 
Sorry, I don't use this with InfluxDB.
Do you try to use InfluxDB histogram() function?

**Comment by mtanda** [comment] 2016-07-08 09:14
I don't promise InfluxDB support, but I'll try to use this with InfluxDB.

**Comment by sikadiamond** [comment] 2016-07-08 09:23
I have not, see: https://docs.influxdata.com/influxdb/v0.13/query_language/functions/#histogram

**Comment by sikadiamond** [comment] 2016-07-08 10:09
I got it to work. Sorry about this.

**Comment by mtanda** [comment] 2016-07-08 10:26
That's great!
Anyway, I'll try to use InfluxDB, and check how this plugin work.

**Comment by mtanda** [comment] 2016-07-11 12:58
I check the behavior of this plugin, when using with InfluxDB.
And, I found a bug, fix it. https://github.com/mtanda/grafana-heatmap-epoch-panel/commit/8800fc30efc7defcca3fbed247daf7f48e9215d6
(Ignore first InfluxDB query which respond empty result.)

**Comment by mtanda** [comment] 2016-08-11 15:34
Should work with InfluxDB, so close this issue.

**Closed as completed by mtanda** 2016-08-11 15:34 UTC
